export const AUTH_FAILED = 'AUTH_FAILED'

/**** AUTH EVENTS  ****/

// LOGIN EVENTS
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

/*--- END AUTH EVENTS  ---*/


/**** USER EVENTS  ****/

export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

export const MODIFY_USER = 'MODIFY_USER'
export const MODIFY_USER_SUCCESS = 'MODIFY_USER_SUCCESS'
export const MODIFY_USER_FAILURE = 'MODIFY_USER_FAILURE'

export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'

/*--- END USER EVENTS  ---*/


/**** ALERT EVENTS  ****/

export const ALL_ALERTS = 'ALL_ALERTS'
export const ALL_ALERTS_SUCCESS = 'ALL_ALERTS_SUCCESS'
export const ALL_ALERTS_FAILURE = 'ALL_ALERTS_FAILURE'

export const ALERT = 'ALERT'
export const ALERT_SUCCESS = 'ALERT_SUCCESS'
export const ALERT_FAILURE = 'ALERT_FAILURE'

export const CREATE_ALERT = 'CREATE_ALERT'
export const CREATE_ALERT_SUCCESS = 'CREATE_ALERT_SUCCESS'
export const CREATE_ALERT_FAILURE = 'CREATE_ALERT_FAILURE'

export const MODIFY_ALERT = 'MODIFY_ALERT'
export const MODIFY_ALERT_SUCCESS = 'MODIFY_ALERT_SUCCESS'
export const MODIFY_ALERT_FAILURE = 'MODIFY_ALERT_FAILURE'

export const DELETE_ALERT = 'DELETE_ALERT'
export const DELETE_ALERT_SUCCESS = 'DELETE_ALERT_SUCCESS'
export const DELETE_ALERT_FAILURE = 'DELETE_ALERT_FAILURE'

/*--- END ALERT EVENTS  ---*/


